#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" == 'master' ]; then
    make deploy
else
    echo 'Not on master branch, skip deploying'
fi

