name: Test and Deploy
on:
  push:
    branches:
      - goshujin

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: "Install pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: "Setup"
        run: pnpm install

      - name: "Build Frontend"
        run: pnpm build:frontend

      - name: "Test"
        run: |
          pnpm fmt
          pnpm lint
          pnpm test

      - name: "Deploy"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          pnpm deploy
