name: PR Tests
on:
  pull_request:

jobs:
  coverage-goshujin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: goshujin

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: "Install pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: "Run Test with Coverage"
        run: |
          pnpm install
          pnpm build:frontend
          pnpm coverage --testTimeout 15000

      - name: "Upload Coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-goshujin
          path: coverage

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: "Install pnpm"
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: "Install Deps"
        run: pnpm install

      - name: "Build Frontend"
        run: pnpm build:frontend

      - name: "Lint"
        run: |
          pnpm prettier -c .
          pnpm lint

      - name: "Type Check"
        run: pnpm typecheck

      - name: "Run Test with Coverage"
        run: pnpm coverage --testTimeout 15000

      - name: "Upload Coverage"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-head
          path: coverage

  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Download HEAD coverage artifacts"
        uses: actions/download-artifact@v4
        with:
          name: coverage-head
          path: coverage

      - name: "Download goshujin coverage artifacts"
        uses: actions/download-artifact@v4
        with:
          name: coverage-goshujin
          path: coverage-goshujin

      - name: "Report Coverage"
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: coverage-goshujin/coverage-summary.json
